# Install: pre-commit install --hook-type pre-push --hook-type commit-msg --install-hooks

default_stages: [pre-push]

repos:
  - repo: local
    hooks:
    
      - id: ruff-check
        name: Ruff check (auto-fix)
        entry: uvx ruff check --fix --config pyproject.toml --force-exclude
        language: system
        types: [python]
        pass_filenames: true

      - id: ruff-format
        name: Ruff format
        entry: uvx ruff format --config pyproject.toml 
        language: system
        types: [python]
        pass_filenames: true

      - id: mypy
        name: Mypy type checking
        entry: uvx mypy --config-file pyproject.toml src
        language: system
        pass_filenames: false

      - id: pytest
        name: Run pytest
        entry: uv run pytest -vv
        language: system
        pass_filenames: false


  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]