site_name: PyChilasLasers Developer Documentation

theme:
  name: material
  logo: assets/star.ico
  features:
    - toc.follow
    - navigation.indexes
    - navigation.footer
    - search.highlight
    - search.share
    - header.autohide
    - navigation.path
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  font:
    text: Fira Sans 
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/chilas/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ChilasLasers
    - icon: simple/mailgun
      link: https://chilasbv.com/contact/
  generator: false


copyright: Copyright &copy; 2025 Chilas B.V.

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]             # <-- make package importable (src layout)
          options:
            docstring_style: google       
            show_inheritance_diagram: true     
            group_by_category: true
            show_category_heading: true
            show_symbol_type_heading: false
            show_symbol_type_toc: true
            merge_init_into_class: true
            members_order: "source"
            # summary: true
            extra:
              ignore_init_summary: true
  - autorefs
  - gen-files:
      scripts:
        - docs/scripts/gendoc.py
        - docs/scripts/gen_tree.py
  - drawio-exporter
  - include-markdown



watch:
  - src                              # live-reload when code changes

nav:
  - Home: index.md
  - Documentation: 
    - package/index.md           
    - package/laser.md
    - package/modes.md
    - Laser Components:
      - package/laser_components/index.md
      - package/laser_components/heaters.md
    - package/comm.md
    - package/exceptions.md
    - package/utils.md
  - Quickstart Guide: quickstart.md
  - Licence: licence.md
  - Readme: readme.md
  - About Chilas: about.md
    


repo_url: https://github.com/ChilasLab/PyChilasLasers

site_author: Chilas B.V.
