[project]
name = "pychilaslasers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.24.4",
    "packaging>=25.0",
    "pyserial>=3.5",
]

[dependency-groups]
dev = [
    "myst-parser>=4.0.1",
    "pip-licenses>=5.0.0",
    "pychilaslasers",
    "sphinx>=8.2.3",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-design>=0.6.1",
    "sphinx-pyreverse>=0.0.18",
    "sphinx-rtd-theme>=3.0.2",
    "sphinx-togglebutton>=0.3.2",
]

[tool.uv.sources]
pychilaslasers = { workspace = true }


[tool.pyright]

reportOptionalMemberAccess = "warning"
reportAttributeAccessIssue = "warning"
