[project]
name = "pychilaslasers"
version = "1.0.0"
description = "Python library for controlling Chilas lasers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "packaging>=25.0",
    "pyserial>=3.5",
]

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-api-autonav>=0.3.1",
    "mkdocs-dracula-theme>=1.0.8",
    "mkdocs-drawio-exporter>=0.10.2",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-literate-nav>=0.6.2",
    "mkdocs-material>=9.6.18",
    "mkdocstrings[python]>=0.30.0",
    "pychilaslasers",
    "pytest>=8.4.1",
]

[tool.uv.sources]
pychilaslasers = { workspace = true }


[tool.pyright]

reportOptionalMemberAccess = "warning"
reportAttributeAccessIssue = "warning"
